ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
}

kaze {
  database {
    driver = "org.postgresql.Driver"
    host = "localhost"
    host = ${?KAZE_DB_HOST}
    port = 5432
    port = ${?KAZE_DB_PORT}
    name = "kaze"
    name = ${?KAZE_DB_NAME}
    user = "postgres"
    user = ${?KAZE_DB_USER}
    password = "Muhirehonore@1*"
    password = ${?KAZE_DB_PASSWORD}
    maximumPoolSize = 10
    maximumPoolSize = ${?KAZE_DB_MAX_POOL_SIZE}
  }
}
